title: Alexa Saunders # your name (or website title) here
logo: "/images/grad.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Results-oriented engineering graduate from Arizona State University. Aiming to leverage computer science academic background with strong presentation skills to successfully fill a role in technical solutions. A passionate solutionist frequently praised as agile-minded by my peers; I can be relied upon to achieve.  
  <br><br>
  <a href="https://www.linkedin.com/in/alexajsaunders/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
